services:
  app:
    build: .
    container_name: ptsr-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "1"   # прогнать prisma migrate deploy при старте
    restart: unless-stopped
